bau: Upgrade mockserver version
Version 3.10.4 is very old, and when uk.gov.pay:testing was being included in
another project it was causing tests in that project to fail with

```
java.lang.IllegalStateException: org.xml.sax.SAXNotRecognizedException:
http://javax.xml.XMLConstants/feature/secure-processing
```

Upgrading mockserver versions solves the problem.

@oswald.quek